SELECT USER
FROM DUAL;
--==>> SCOTT


-- 학생 테이블 생성
CREATE TABLE TBL_STUDENT
( SID   NUMBER
, NAME  VARCHAR2(30)
, TEL   VARCHAR2(40)
, CONSTRAINT STUDENT_SID_PK PRIMARY KEY(SID)
);
--==>> Table TBL_STUDENT이(가) 생성되었습니다.

CREATE SEQUENCE STUDENTSEQ
NOCACHE;
--==>> Sequence STUDENTSEQ이(가) 생성되었습니다.

INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(STUDENTSEQ.NEXTVAL, '이새롬', '010-1111-1111');
INSERT INTO TBL_STUDENT(SID, NAME, TEL)
VALUES(STUDENTSEQ.NEXTVAL, '김아별', '010-2222-2222');
--==>> 1 행 이(가) 삽입되었습니다.


-- 성적 테이블 생성
CREATE TABLE TBL_GRADE
( SID   NUMBER
, SUB1  NUMBER(3)
, SUB2  NUMBER(3)
, SUB3  NUMBER(3)
, CONSTRAINT GRADE_SID_PK PRIMARY KEY(SID)
, CONSTRAINT GRADE_SID_FK FOREIGN KEY(SID)
             REFERENCES TBL_STUDENT(SID)
);
--==>> Table TBL_GRADE이(가) 생성되었습니다.

INSERT INTO TBL_GRADE(SID, SUB1, SUB2, SUB3)
VALUES(1, 90, 100, 95);
--==>> 1 행 이(가) 삽입되었습니다.


-- 학생 뷰 생성 
CREATE OR REPLACE VIEW STUDENTVIEW
AS
SELECT SID, NAME, TEL
, (SELECT COUNT(*)
FROM TBL_GRADE
WHERE SID=S.SID) SUB
FROM TBL_STUDENT S;
--==>> View STUDENTVIEW이(가) 생성되었습니다.

SELECT SID, NAME, TEL, SUB
FROM STUDENTVIEW;
--==>> 1	이새롬	010-1111-1111	1

SELECT COUNT(*) AS COUNT
FROM TBL_STUDENT;
--==>> 1


-- 성적 뷰 생성 
CREATE OR REPLACE VIEW GRADEVIEW
AS
SELECT SID,
(   
    SELECT NAME
    FROM TBL_STUDENT
    WHERE SID = G.SID
) NAME
, SUB1, SUB2, SUB3
, (SUB1+SUB2+SUB3) TOT
, ((SUB1+SUB2+SUB3)/3.0) AVG
, (SELECT 
    CASE 
        WHEN (SUB1+SUB2+SUB3)/3.0>90 THEN 'A'
        WHEN (SUB1+SUB2+SUB3)/3.0>80 THEN 'B'
        WHEN (SUB1+SUB2+SUB3)/3.0>70 THEN 'C'
        WHEN (SUB1+SUB2+SUB3)/3.0>60 THEN 'D'
        ELSE 'F'
    END
FROM TBL_GRADE) CH
FROM TBL_GRADE G;
--==>> View GRADEVIEW이(가) 생성되었습니다.

SELECT SID, NAME, SUB1, SUB2, SUB3, TOT, AVG, CH
FROM GRADEVIEW;
--==>> 1	이새롬	90	100	95	285	95	A

SELECT COUNT(*) AS COUNT
FROM TBL_GRADE;
--==>> 1

-- 커밋
COMMIT;

-- 초기화
DELETE
FROM TBL_STUDENT;

DELETE
FROM TBL_GRADE;

DROP SEQUENCE STUDENTSEQ;

